### ISSUE TITLE
code error CS0246

### ISSUE THREAD

**Issue by shiaumo-company** [YBTopaz8/FlowHub-MAUI#89]
When executing '**MauiProgram.cs**,' an error (CS0246) is encountered, indicating the absence of '**OnlineDataAccessRepository**' at line 58. Please verify the existence of the file. If it exists, it should be located within the **FlowHub.DataAccess-Repositories** directory.
thank you!!!

**Comment by YBTopaz8** [comment]
Hi !
So, you need to create the file `OnlineDataAccessRepository.cs` under the folder `FlowHub.DataAccess/Platforms/Android/` and `FlowHub.DataAccess/Platforms/Windows/`
and add the codes as shown in these samples found in this commit here:
 https://github.com/YBTopaz8/FlowHub-MAUI/commit/72199ecdd71b747ac4f74c8ab2151358eaac5fcc?diff=split&w=0

the Android Sample file can be seen here : https://github.com/YBTopaz8/FlowHub-MAUI/commit/72199ecdd71b747ac4f74c8ab2151358eaac5fcc?diff=unified&w=0#diff-424393bc326f703504f093cdddcedcdbeaebf6caba2679bc83d976648bae5749

The Windows Sample file can be seen here : https://github.com/YBTopaz8/FlowHub-MAUI/commit/72199ecdd71b747ac4f74c8ab2151358eaac5fcc?diff=unified&w=0#diff-e3c969699c1c6578bce766844ade74cf9fd75b956e2fb0910395e8d7237e8120

Feel free to ask if you have any other questions. 
More Issues and suggestions are welcome (as i can't think of everything 😅)
